### ISSUE TITLE
Failed to load external converter file 'avatto_me167.js' (Cannot find module 'zigbee-herdsman-converters/lib/extend'

### ISSUE THREAD

**Issue by StefanLobbenmeier** [sychu/avatto_me167_TZE200_p3dbf6qs#2]
Worked well in the past, but after updating zigbee2mqtt it is no longer compatible

**Comment by StefanLobbenmeier** [comment]
Can be easily fixed though by just removing the import of extend, it is not used

**Comment by HubEight** [comment]
> Can be easily fixed though by just removing the import of extend, it is not used

Thanks for the hint, it worked!

**Comment by sychu** [comment]
> Can be easily fixed though by just removing the import of extend, it is not used

@StefanLobbenmeier thanks for info, extend removed.
